---
- hosts: 10.10.10.62
  remote_user: root
  vars_prompt:
    - name: choose
      prompt: " *** 请选择安装JDK版本 **** \n 1、安装JDK 1.8.0_261\n 2、安装JDK 1.8.0_281 \n ( 请输入序号 ) "
      private: no
  tasks:
    - name: 01-JDK catalog is exists
      shell: find /usr/local/ -type d -name "jdk1.8"
      register:
        jdkinfo
        
    - name: 02-unarchive jdk_1.8.0._261 file
      ansible.builtin.unarchive:
        src: /etc/ansible/roles/JDK/files/jdk-8u261-linux-x64.tar.gz
        dest: /usr/local/
        owner: root
        group: root
      when: choose == "1" and jdkinfo.stdout != "/usr/local/jdk1.8"

    - name: 03-modify jdk_1.8.0._261 file name
      shell: mv /usr/local/jdk1.8.0_261 /usr/local/jdk1.8
      when: choose == "1" and jdkinfo.stdout != "/usr/local/jdk1.8"
 
    - name: 04-unarchive jdk_1.8.0._281 file
      ansible.builtin.unarchive:
        src: /etc/ansible/roles/JDK/files/jdk-8u281-linux-x64.tar.gz
        dest: /usr/local/
        owner: root
        group: root
      when: choose == "2" and jdkinfo.stdout != "/usr/local/jdk1.8"

    - name: 05-modify jdk_1.8.0._281 file name
      shell: mv /usr/local/jdk1.8.0_281 /usr/local/jdk1.8
      when: choose == "2" and jdkinfo.stdout != "/usr/local/jdk1.8"

    - name: 06-add JDK configuration
      ansible.builtin.lineinfile:
        dest: /etc/profile
        line: "{{ item }}"
      with_items:
        - export JAVA_HOME=/usr/local/jdk1.8
        - export JRE_HOME=$JAVA_HOME/jre
        - export CLASSPATH=.:\$JAVA_HOME/lib/dt.jar:\$JAVA_HOME/lib/tools.jar
        - export PATH=$PATH:/$JAVA_HOME/bin 

    - name: 07-variables enforce
      shell: source /etc/profile
