---
- hosts: 10.10.10.62
  remote_user: root
  vars_prompt:
    - name: choose
      prompt: " *** 请选择安装JDK版本 **** \n 1、安装JDK 1.8.0_261\n 2、安装JDK 1.8.0_281 \n ( 请输入序号 ) "
      private: no
  tasks:
    - name: 01-unarchive jdk_1.8.0._261 file
      ansible.builtin.unarchive:
        src: /etc/ansible/roles/JDK/files/jdk-8u261-linux-x64.tar.gz
        dest: /usr/local/
        owner: root
        group: root
      when: choose == "1"

    - name: 02-modify jdk_1.8.0._261 file name
      ansible.builtin.shell: mv /usr/local/jdk1.8.0_261 /usr/local/jdk1.8
      when: choose == "1"
 
    - name: 03-unarchive jdk_1.8.0._281 file
      ansible.builtin.unarchive:
        src: /etc/ansible/roles/JDK/files/jdk-8u281-linux-x64.tar.gz
        dest: /usr/local/
        owner: root
        group: root
      when: choose == "2"

    - name: 04-modify jdk_1.8.0._281 file name
      ansible.builtin.shell: mv /usr/local/jdk1.8.0_281 /usr/local/jdk1.8
      when: choose == "2"

    - name: 05-add JDK configuration
      ansible.builtin.lineinfile:
        dest: /etc/profile
        line: "{{ item }}"
      with_items:
        - export JAVA_HOME=/usr/local/jdk1.8
        - export JRE_HOME=$JAVA_HOME/jre
        - export CLASSPATH=.:\$JAVA_HOME/lib/dt.jar:\$JAVA_HOME/lib/tools.jar
        - export PATH=$PATH:/$JAVA_HOME/bin 

    - name: 06-variables enforce
      ansible.builtin.shell: source /etc/profile
