---
- hosts: zabbixclient
  remote_user: root
  tasks:
  - name: 01-create zabbix user
    ansible.builtin.user:
      name: zabbix
      groups:
      state: present
      shell: /sbin/nologin
      create_home: no

  - name: 02-create zabbix agent directory
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      owner: zabbix
      group: zabbix
    with_items:
      - /etc/zabbix
      - /etc/zabbix/zabbix_agentd.d

  - name: 03-uncompress zabbix_agent package
    ansible.builtin.unarchive:
      src: /etc/ansible/roles/zabbix_client/files/zabbix_agent-4.0.21-linux-3.0-amd64-static.tar.gz
      dest: /etc/zabbix
      owner: zabbix
      group: zabbix

  - name: 04-add zabbix agent port in /etc/services tail
    ansible.builtin.lineinfile:
      path: /etc/services
      line: "{{ item }}"
      state: present 
    with_items:
      - zabbix_agent   10050/tcp
      - zabbix_agent   10050/udp
      
  - name: 05-copy zabbix_agent start file
    copy:
      src: /etc/zabbix/sbin/zabbix_agentd
      dest: /etc/init.d/zabbix_agentd
      remote_src: yes
      mode: '755'

  - name: 06-copy zabbix agent systemctl configuration
    ansible.builtin.template:
      src: /etc/ansible/roles/zabbix_client/templates/zabbix-agent.service
      dest: /usr/lib/systemd/system/

  - name: 07-copy zabbix agent configuration
    ansible.builtin.template:
      src: /etc/ansible/roles/zabbix_client/templates/zabbix_agentd.conf.j2
      dest: /etc/zabbix/conf/zabbix_agentd.conf

  - name: 08-start and enable zabbix agent service
    ansible.builtin.systemd:
      daemon_reload: yes
      name: zabbix-agent.service
      state: started
      enabled: yes

### 注意: regexp匹配字符串如果遇到特殊符号'+'需要添加'\'进行转义
  - name: 09-clean ssh login record
    ansible.builtin.lineinfile:
      path: /root/.ssh/authorized_keys
      regexp: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCxlV4ysQvGsxdm03423000CoGwB6b5GAVXumTI6sdfdsfds3337U2brU7m20JmhfYU4GKPYbO\+PftFceeww3cfQgj\+utFmFKdjNOM5JxRvnStEjUHNzKqm/yXQPm\+4wkiJRWXEAGlJUa7irZIg55H/AhTlV55SsidgTIz5UF65\+uOsCvyxLY3nW3WiiGVbwqiUU\+fNdonsV5MvI9mdtOQwX/4iiS62vPHElGaHIZIa7tOa0yrxuqGzbocvQf9XOVdgiRIOVddn6GkN9cU0qP8Q1CZQ8wkfJGeI6b15mmKW4HG9IQwSlkZdpmDpx8vFixOgwc450mD8/BUIaTcxElweDhqQYW7Ujx root@hanszabbix'
      state: absent
